# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinglala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_no',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
