# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xinglala', '0002_product_brand_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='xinglala_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
